name: reinforcement_learning
channels:
  - salilab
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.08.22=hecd8cb5_0
  - libffi=3.4.4=hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.12=hca72f7f_0
  - pip=23.3.1=py310hecd8cb5_0
  - python=3.10.13=h5ee71fb_0
  - readline=8.2=hca72f7f_0
  - setuptools=68.0.0=py310hecd8cb5_0
  - sqlite=3.41.2=h6c40b1e_0
  - tk=8.6.12=h5d9f67b_0
  - wheel=0.41.2=py310hecd8cb5_0
  - xz=5.4.5=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - biopandas==0.4.1
      - biopython==1.81
      - certifi==2023.11.17
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.10
      - dgl==1.1.2.post1
      - dgllife==0.3.2
      - filelock==3.13.1
      - fonttools==4.47.0
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - future==0.18.3
      - hyperopt==0.2.7
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.10.1
      - matplotlib==3.8.2
      - mmtf-python==1.1.3
      - moleculekit==1.8.17
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.5
      - networkx==3.2.1
      - numpy==1.26.2
      - packaging==23.2
      - pandas==2.1.4
      - pillow==10.1.0
      - prettytable==3.9.0
      - py4j==0.10.9.7
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch-lightning==2.2.1
      - pytz==2023.3.post1
      - rmsd==1.5.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.0
      - six==1.16.0
      - sympy==1.12
      - threadpoolctl==3.2.0
      - torch==2.2.1
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2
      - torchmetrics==1.3.1
      - torchvision==0.17.1
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - yacs==0.1.8
      - yarl==1.9.4
prefix: /Users/xw0201/opt/anaconda3/envs/reinforcement_learning
